build:
  version: V1

application:
  message: "Welcome to Application service of jobconnect (live)"
  contactDetails:
    name: Rohan Jha (Local)
    email: Rohanjhaaa@gmail.com
  onCallSupport:
    -(+91)8823995323
    -(+91)7723995322
  hostname: eurekaserver
  eureka:
    port: 5005

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:5005/eureka/}

info:
  app:
    name: "applications"
    description: "Job connect application service"
    version: "1.0"
