build:
  version: V1

application:
  message: "Welcome to Application service of jobconnect (live test controlled added)"
  contactDetails:
    name: Rohan Jha (Local)
    email: Rohanjhaaa@gmail.com
  onCallSupport:
    -(+91)8823995323
    -(+91)7723995322
